"""Run example scenarios, grouped by the topology of the domain.

Usage::

    python -m rps_diffusion.examples                    # everything, plus examples/GALLERY.md
    python -m rps_diffusion.examples annulus            # one group
    python -m rps_diffusion.examples annulus.ring_rotating_wave   # one scenario
    python -m rps_diffusion.examples --list             # show what is available
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from rps_diffusion.examples import GROUPS
from rps_diffusion.examples._common import OUTPUT_DIR, Group, Scenario, run_scenario

GALLERY = Path("examples") / "GALLERY.md"


def _select(targets: list[str]) -> list[tuple[Group, Scenario]]:
    by_key = {g.key: g for g in GROUPS}
    if not targets:
        return [(g, s) for g in GROUPS for s in g.scenarios]
    chosen: list[tuple[Group, Scenario]] = []
    for target in targets:
        group_key, _, name = target.partition(".")
        if group_key not in by_key:
            sys.exit(f"unknown group {group_key!r}; choose from {', '.join(by_key)}")
        group = by_key[group_key]
        scenarios = [s for s in group.scenarios if not name or s.name == name]
        if not scenarios:
            sys.exit(f"unknown scenario {target!r}; run with --list")
        chosen += [(group, s) for s in scenarios]
    return chosen


def _rel(path: Path) -> str:
    return Path(path).relative_to(GALLERY.parent).as_posix()


def _write_gallery(results: dict[tuple[str, str], dict]) -> None:
    lines = [
        "# Example gallery",
        "",
        "Generated by `python -m rps_diffusion.examples`. Scenarios are grouped by the topology",
        "of the domain. Every summary figure shows the mean fractions and their spectrum",
        "(top), the initial distributions (middle) and the final distributions (bottom).",
        "The title lists σ, the three rates, the fixed point ρ* and ω₀.",
        "",
    ]
    for g in GROUPS:
        lines += [f"## {g.title}", "", g.description, ""]
        for s in g.scenarios:
            info = results[(g.key, s.name)]
            peaks = ", ".join(f"{p:.3f}" for p in info["peaks"])
            lo, hi = info["range"]
            lines += [
                f"### `{g.key}.{s.name}`",
                "",
                s.description,
                "",
                f"- predicted f₀ = ω₀/2π = {info['f0']:.3f}; measured spectral peaks: {peaks}",
                f"- mean fractions range over [{lo:.3f}, {hi:.3f}]",
                *[f"- winding number {label}: {w0:+.2f} at the start, {w1:+.2f} at the end"
                  for label, w0, w1 in info["windings"]],
                "",
                f"![{s.name} video]({_rel(info['video'])})",
                "",
                f"![{s.name} summary]({_rel(info['png'])})",
                "",
            ]
    GALLERY.write_text("\n".join(lines), encoding="utf-8")
    print(f"gallery -> {GALLERY}")


def main(argv: list[str] | None = None) -> None:
    """Command-line entry point."""
    parser = argparse.ArgumentParser(prog="python -m rps_diffusion.examples", description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("targets", nargs="*", help="group or group.scenario (default: all)")
    parser.add_argument("--list", action="store_true", help="list groups and scenarios and exit")
    args = parser.parse_args(argv)

    if args.list:
        for g in GROUPS:
            print(f"{g.key}: {g.title}")
            for s in g.scenarios:
                print(f"  {g.key}.{s.name}")
        return

    results = {(g.key, s.name): run_scenario(g, s, OUTPUT_DIR) for g, s in _select(args.targets)}
    if not args.targets:
        _write_gallery(results)


if __name__ == "__main__":
    main()
